# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.24
_src_path: gh:oca/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 16.0
org_name: Akretion
org_slug: Akretion
rebel_module_groups: []
repo_description: Accounts Receivable Factoring for Odoo
repo_name: Odoo Factoring
repo_slug: https://github.com/akretion/odoo-factoring/tree/16.0
repo_website: https://github.com/akretion/odoo-factoring
use_pyproject_toml: true
use_ruff: true

